export const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    CONFLICT: 'CONFLICT',
    SEAT_ALREADY_RESERVED: 'SEAT_ALREADY_RESERVED',
    EVENT_FULL: 'EVENT_FULL',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    INVALID_BOOKING_STATE: 'INVALID_BOOKING_STATE',
} as const;
